stages:
  - build
  - upload
#  - release

variables:
    # Package version can only contain numbers (0-9), and dots (.).
    # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
    XZ_DEFAULTS: "-T 0"
    PACKAGE_FILE: lx2160a-firmware_${CI_COMMIT_SHORT_SHA}.tar.xz
    PACKAGE_VERSION: "1.0.0"
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/lx2k-firmware/${PACKAGE_VERSION}"
    DEBIAN_FRONTEND: "noninteractive"

build:
  stage: build
  image: hammerkeg/kernel_build_gcc10
  rules:
    - if: $CI_COMMIT_SHORT_SHA
  script:
    - INITIALIZE=1 ./runme.sh
    - patch build/tianocore/edk2-platforms/Platform/SolidRun/LX2160aCex7/LX2160aCex7.dsc < pwm.patch
    - ./runme.sh
    - SERDES=20_5_2 ./runme.sh
    - tar -cJf ${PACKAGE_FILE} images/*
    - CLEAN=1 ./runme.sh
  artifacts:
      paths:
        - ${PACKAGE_FILE}

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_SHORT_SHA
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${PACKAGE_FILE} ${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}